clean up of mml script and help messages

diff --git a/bin/mml b/bin/mml
--- a/bin/mml
+++ b/bin/mml
@@ -21,18 +21,21 @@ EOF
 }
 
 getprog() {
-    local it="$MML_ROOT/bin/mml-$1"
-    if [ -f $it ]; then
-	PROG="$it"
+    local x=$(trim "$1")
+    local f="$MML_ROOT/bin/mml-$x"
+    if [ -f $f ]; then
+	echo -n "$f"
+	exit 0
     else
-	if test -z "$1"; then
-            echo "*** error: mml:" required command not found
-	else
-	    echo "*** error: mml:" receieved unrecognized command \'"$1"\'
+	if [ ! -z "$x" ]; then
+	    echo -n "error: mml: $x: unrecognized command"
 	fi
-	usage
 	exit 1
     fi
+}
+
+trim() {
+    echo -n $(echo "$1" | sed "s/\(^ *\| *\$\)//g")
 }
 
 resolvelinks() {
@@ -79,13 +82,13 @@ resolvelinks() {
         fi
 
         # Now resolve the symbolic link "$f"
-        f_resolved=`readlink -n "$out$f" 2>/dev/null`
+        f_resolved=$(readlink -n "$out$f" 2>/dev/null)
         status=$?
         # status 127 means readlink could not be found.
         if [ $status -eq 127 ]; then
             # We don't have "readlink", try a stupid "ls" hack instead.
             # This will fail if we have filenames like "a -> b".
-            fls=`ls -l "$out$f" 2>/dev/null`
+            fls=$(ls -l "$out$f" 2>/dev/null)
             status=$?
             f_resolved=${fls##*-> }
 
@@ -106,23 +109,23 @@ resolvelinks() {
     done
 
     # Return $out
-    echo "$out"
+    echo -n "$out"
 }
 
 # If MML_ROOT is not given, find it out from $0
 if [ -z "$MML_ROOT" ];  then
     # Get the path to $0 (this shell script) with all symbolic links
     # resolved
-    THIS_DIR=`resolvelinks "$0"` || THIS_DIR="$0"
+    d=$(resolvelinks "$0") || d="$0"
 
     # Get the directory component
-    THIS_DIR="${THIS_DIR%/*}"
-    THIS_DIR=`cd "$THIS_DIR" && pwd -P`
-    MML_ROOT="$(dirname "$THIS_DIR")"
+    d="${d%/*}"
+    d=$(cd "$d" && pwd -P)
+    MML_ROOT="$(dirname "$d")"
 fi
 
 # Make MML_ROOT absolute
-MML_ROOT=`cd "$MML_ROOT" && pwd -P`
+MML_ROOT=$(cd "$MML_ROOT" && pwd -P)
 if [ $? -ne 0 ]; then
     echo >&2 "$0: cannot determine MML_ROOT directory"
     exit 1
@@ -131,7 +134,7 @@ fi
 export MML_ROOT
 export PATH="$MML_ROOT/bin:$PATH"
 export PYTHONPATH="$MML_ROOT:$PYTHONPATH"
-export PYTHONEXEC=$(which python)
+export MML_PY_EXE=$(which python)
 
 # option parsing - for now, only -h is supported
 while getopts "h" OPTION
@@ -150,18 +153,27 @@ do
 done
 
 # positional parameters
-COMMAND="$1"
+cmd=$(trim "$1")
 shift
-if [ "$COMMAND" == "help" ];
+if [ "$cmd" == "help" ];
 then
-    COMMAND="$1"
-    if [ "$COMMAND" == "" ];
+    cmd=$(trim "$1")
+    if [ "$cmd" == "" ];
     then
         usage
         exit 0
     fi
     set -- "-h"
 fi
-getprog "$COMMAND"
 
-$PROG "$@"
+X=$(getprog "$cmd")
+if [ $? -ne 0 ]; then
+    if [ ! -z "$X" ];
+    then
+	echo "mml: '$cmd' is not a mml command.  See 'mml -h'."
+    else
+	usage
+    fi
+    exit 1
+fi
+$X "$@"
diff --git a/bin/mml-build b/bin/mml-build
--- a/bin/mml-build
+++ b/bin/mml-build
@@ -1,8 +1,9 @@
 #!/usr/bin/env bash
-# set up python environment
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-ROOT="$(dirname "$DIR")"
-export PYTHONPATH="$ROOT"
-PYFILE="$ROOT/core/builder.py"
-PYTHON=$(which python)
-$PYTHON $PYFILE "$@"
+if [ -z "$MML_ROOT" ];  then
+    echo >&2 "*** error: mml-build: MML_ROOT environment variable not set"
+    echo >&2 "this script should be called through matmodlab/bin/mml"
+    echo >&2 "and not directly"
+    exit 1
+fi
+PYFILE="$MML_ROOT/core/builder.py"
+$MML_PY_EXE $PYFILE "$@"
diff --git a/bin/mml-clean b/bin/mml-clean
--- a/bin/mml-clean
+++ b/bin/mml-clean
@@ -1,8 +1,11 @@
 #!/usr/bin/env bash
 # set up python environment
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-ROOT="$(dirname "$DIR")"
-
+if [ -z "$MML_ROOT" ];  then
+    echo >&2 "*** error: mml-clean: MML_ROOT environment variable not set"
+    echo >&2 "this script should be called through matmodlab/bin/mml"
+    echo >&2 "and not directly"
+    exit 1
+fi
 usage()
 {
 cat << EOF
@@ -28,8 +31,9 @@ do
      esac
 done
 
-find $ROOT \( -type d -name "build" -o -type d -name "*.eval" \) -exec rm -rf {} \+
-find $ROOT \( -name "*.pyc" -o -name "*.o" -o \
-              -name "*.con" -o -name "*.a" -o \
-              -name "*-f2pywrappers2.f90" -o -name "*module.c" -o \
-              -name "*.so"  -o -name "*.log"  \) -exec rm -f {} \+
+find $MML_ROOT \( -type d -name "build" -o -type d -name "*.eval" \) \
+                  -exec rm -rf {} \+
+find $MML_ROOT \( -name "*.pyc" -o -name "*.o" -o \
+                  -name "*.con" -o -name "*.a" -o \
+                  -name "*-f2pywrappers2.f90" -o -name "*module.c" -o \
+                  -name "*.so"  -o -name "*.log"  \) -exec rm -f {} \+
diff --git a/bin/mml-run b/bin/mml-run
--- a/bin/mml-run
+++ b/bin/mml-run
@@ -1,18 +1,19 @@
 #!/bin/bash
-# set up python environment
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-ROOT="$(dirname "$DIR")"
-export PYTHONPATH="$ROOT"
-PYTHON=$(which python)
+if [ -z "$MML_ROOT" ];  then
+    echo >&2 "*** error: mml-run: MML_ROOT environment variable not set"
+    echo >&2 "this script should be called through matmodlab/bin/mml"
+    echo >&2 "and not directly"
+    exit 1
+fi
 while getopts "h" OPTION
 do
      case $OPTION in
          h)
 	    # run typically operates directly on a python file - which calls
 	    # clparse through matmodlab.py, here we call clparse directly
-	     $PYTHON $ROOT/utils/clparse.py -h
+	     $MML_PY_EXE $MML_ROOT/utils/clparse.py -h
              exit 0
              ;;
      esac
 done
-$PYTHON "$@"
+$MML_PY_EXE "$@"
diff --git a/bin/mml-test b/bin/mml-test
--- a/bin/mml-test
+++ b/bin/mml-test
@@ -1,8 +1,9 @@
 #!/usr/bin/env bash
-# set up python environment
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-ROOT="$(dirname "$DIR")"
-export PYTHONPATH="$ROOT"
-PYFILE="$ROOT/core/tester.py"
-PYTHON=$(which python)
-$PYTHON $PYFILE "$@"
+if [ -z "$MML_ROOT" ];  then
+    echo >&2 "*** ERROR: $0: MML_ROOT ENVIRONMENT VARIABLE NOT SET"
+    echo >&2 "THIS SCRIPT SHOULD BE CALLED THROUGH matmodlab/bin/mml"
+    echo >&2 "AND NOT DIRECTLY"
+    exit 1
+fi
+PYFILE="$MML_ROOT/core/tester.py"
+$MML_PY_EXE $PYFILE "$@"
