Several disjoint updates/fixes
o Update to command line processing.  Especially for the mml run command.
o Changed the plotting around some.  Better color choosing.  Moved to
  the core/ directory.
o Removed the other viz stuff.  Maybe someone will resurrect it in the
  future, but for now all of the files are nonfunctional, except the plotting.
o removed old xpython script and related
o added bin/mml-python
o moved core/mat_point_sim to core/simulator (more consistent with other file names).
o big clean up to the path parsing.
o clean up to some raised errors.
o new test for path table functionality.
o bug fix running tests with rc nprocs

diff --git a/bin/mml-python b/bin/mml-python
--- a/bin/mml-python
+++ b/bin/mml-python
@@ -1,10 +1,9 @@
-#!/usr/bin/env bash
+#!/bin/bash
 if [ -z "$MML_ROOT" ];  then
-    echo >&2 "*** error: mml-config: MML_ROOT environment variable not set"
+    echo >&2 "*** error: mml-run: MML_ROOT environment variable not set"
     echo >&2 "this script should be called through matmodlab/bin/mml"
     echo >&2 "and not directly"
     exit 1
 fi
-PYFILE="$MML_ROOT/core/configurer.py"
 PYEXE=$(which python)
-$PYEXE $PYFILE "$@"
+$PYEXE "$@"
diff --git a/bin/mml-view b/bin/mml-view
--- a/bin/mml-view
+++ b/bin/mml-view
@@ -1,8 +1,10 @@
-#!/usr/bin/env python
-import os
-import sys
-d = os.path.dirname(os.path.realpath(__file__))
-sys.path.insert(0, os.path.dirname(d))
-from matmodlab import *
-from viz.plot2d import main
-sys.exit(main(sys.argv[1:]))
+#!/usr/bin/env bash
+if [ -z "$MML_ROOT" ];  then
+    echo >&2 "*** ERROR: mml-view: MML_ROOT ENVIRONMENT VARIABLE NOT SET"
+    echo >&2 "THIS SCRIPT SHOULD BE CALLED THROUGH matmodlab/bin/mml"
+    echo >&2 "AND NOT DIRECTLY"
+    exit 1
+fi
+PYFILE="$MML_ROOT/core/plotter.py"
+PYEXE=$(which python)
+$PYEXE $PYFILE "$@"
